name: Basic build with badges generation
on: [push]
jobs:
  build_job: # job name
    runs-on: ubuntu-22.04
    steps:
      - name: Standard Checkout
        uses: actions/checkout@v3.2.0

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.8.1
        with:
          generate-branches-badge: true